### ISSUE TITLE
Emoji Layout

### ISSUE THREAD

**Issue by ryanbrownhill** [una/animated-emojis#1]
Shall we place the emojis in a div so they keep the same layout at the original dribbble - would help with keeping track of the emojis we are working on.  Or at least we would make them 7 across whenever possible.  :+1: 

![Emjois](https://camo.githubusercontent.com/b96a19622dcc71d6070f345c5eac3162e517d87d/68747470733a2f2f6431337961637572716a676172612e636c6f756466726f6e742e6e65742f75736572732f34333736322f73637265656e73686f74732f313932353730382f656d6f6a69732e676966)

**Comment by una** [comment]
Nah we will deal with layout later
